storage_path: /storage
docker_containers_dir: /opt/containers

timezone: Europe/Madrid
PUID: 1000
PGID: 1000

packages:
  - curl
  - vim
  - git
  - unrar-free
  - htop
  - cockpit
  - udisks2-lvm2
  - udisks2-btrfs

network:
  # Interfaz a configurar. Si se deja vacia se autodetecta usando la ruta por
  # defecto del servidor (ansible_facts.default_ipv4.interface).
  interface: ""
  address: 192.168.122.100
  prefix: 24
  gateway: 192.168.122.1
  dns:
    - 9.9.9.9
    - 149.112.112.112

homeserver_name: homeserver
homeserver_domain: omp.home

