services:
  filebrowser:
    image: gtstef/filebrowser:stable
    user: filebrowser
    volumes:
      - ${STORAGE}/filebrowser:/srv
      - filebrowser_config:/home/filebrowser/data
    ports:
      - 8082:80
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`filebrowser.omp.home`)"
      - "traefik.http.routers.filebrowser.entrypoints=web"
      - "traefik.http.services.filebrowser.loadbalancer.server.port=8082"

volumes:
  filebrowser_config:
    external: true

networks:
  traefik-net:
    external: true
