#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Load modules
source "$SCRIPT_DIR/lib/env.sh"
source "$SCRIPT_DIR/lib/stacks.sh"
source "$SCRIPT_DIR/lib/volumes.sh"
source "$SCRIPT_DIR/lib/checks.sh"

# Order matters
STACKS=("filebrowser" "flame" "gitea" "jellyfin" "joplin" "kopia" "media-stack" "metube" "traefik" )
VOLUMES=("filebrowser_config" "flame_data" "gitea_data" "jellyfin_data" "joplin_data" "kopia_config" "qbittorrent_data" "prowlarr_data" "sonarr_data" "radarr_data" "bazarr_data" "jackett_data")

COMMAND="${1:-}"

usage() {
  cat <<EOF
Uso:
  stackctl up
  stackctl down
  stackctl dry-run
  stackctl purge-volumes
  stackctl status
EOF
}

case "$COMMAND" in
  up)
    load_env
    check_structure
    create_volumes
    deploy_stacks
    ;;

  down)
    down_stacks
    ;;

  dry-run)
    echo "[DRY-RUN] Validando infraestructura..."
    check_structure
    check_volumes
    ;;

  purge-volumes)
    delete_volumes
    ;;

  status)
    docker ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"
    ;;

  *)
    usage
    exit 1
    ;;
esac
