services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - jackett_data:/config:Z
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jackett.rule=Host(`jackett.omp.home`)"
      - "traefik.http.routers.jackett.entrypoints=web"
      - "traefik.http.services.jackett.loadbalancer.server.port=9117"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - WEBUI_PORT=8090
      # - TORRENTING_PORT=6881
    volumes:
      - qbittorrent_data:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 8090:8090
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.omp.home`)"
      - "traefik.http.routers.qbittorrent.entrypoints=web"
      - "traefik.http.services.qbittorrent.loadbalancer.server.port=8090"

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - prowlarr_data:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.omp.home`)"
      - "traefik.http.routers.prowlarr.entrypoints=web"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    volumes:
      - sonarr_data:/config:Z
      - ${STORAGE}/torrents:/downloads:Z
      - ${STORAGE}/media/tv:/storage/TV:Z
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: unless-stopped
    depends_on:
      - jackett
      - prowlarr
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.omp.home`)"
      - "traefik.http.routers.sonarr.entrypoints=web"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    volumes:
      - radarr_data:/config:Z
      - ${STORAGE}/torrents:/downloads:Z
      - ${STORAGE}/media/movies:/storage/Movies:Z
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    restart: unless-stopped
    depends_on:
      - jackett
      - prowlarr
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.omp.home`)"
      - "traefik.http.routers.radarr.entrypoints=web"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - bazarr_data:/config:Z
      - ${STORAGE}/media/movies:/movies:Z
      - ${STORAGE}/media/tv:/tv:Z
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.omp.home`)"
      - "traefik.http.routers.bazarr.entrypoints=web"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"

volumes:
  qbittorrent_data:
    external: true
  prowlarr_data:
    external: true
  sonarr_data:
    external: true
  radarr_data:
    external: true
  bazarr_data:
    external: true
  jackett_data:
    external: true

networks:
  traefik-net:
    external: true
