---
- name: Configuración específica de Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts.distribution == "Debian"

- name: Configuración específica de Ubuntu
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts.distribution == "Ubuntu"
