---
- name: Gather package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Configure network on Ubuntu
  ansible.builtin.template:
    src: netplan.j2
    dest: /etc/netplan/99-ansible-network.yaml
    owner: root
    group: root
    mode: '0600'
    backup: true

- name: Validar la configuracion generada por netplan
  ansible.builtin.command:
    cmd: netplan generate
  changed_when: false
