services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERURL=${IP}
      - SERVERPORT=51820
      - PEERS=2
      - PEERDNS=9.9.9.9
      - INTERNAL_SUBNET=10.0.0.0
      - ALLOWEDIPS=0.0.0.0/0
      # - PERSISTENTKEEPALIVE_PEERS=
      # - LOG_CONFS=true
    ports:
      - 51820:51820/udp
    volumes:
      - ${PATH_CONFIG}/wireguard:/config:Z
      - ${PATH_CONFIG}/wireguard/lib/modules:/lib/modules:Z
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

volumes:
  wireguard_conf:
    external: true
  wireguard_modules:
    external: true
