- name: Check that storage path exists
  ansible.builtin.stat:
    path: "{{ storage_path }}"
  register: storage_path_check

- name: Fail if storage path does not exist
  ansible.builtin.fail:
    msg: "The storage path '{{ storage_path }}' does not exist."
  when: not storage_path_check.stat.exists

- name: Create service storage local directories
  ansible.builtin.file:
    path: "{{ item.1 }}"
    state: directory
    owner: "{{ item.0.storage_local.owner }}"
    group: "{{ item.0.storage_local.group }}"
    mode: "0755"
  loop: "{{ services | subelements('storage_local.directories', skip_missing=True) }}"
  loop_control:
    label: "{{ item.1 }}"

- name: Create per-service compose directories
  file:
    path: "{{ docker_containers_dir }}/{{ item.name }}"
    state: directory
    owner: "{{ PUID | default(1000) }}"
    group: "{{ PGID | default(1000) }}"
    mode: '0755'
  loop: "{{ services }}"

- name: Deploy container compose files
  template:
    src: "{{ item.name }}.yml.j2"
    dest: "{{ docker_containers_dir }}/{{ item.name }}/compose.yml"
  loop: "{{ services }}"

- name: Deploy .env files
  template:
    src: "{{ item.name }}.env.j2"
    dest: "{{ docker_containers_dir }}/{{ item.name }}/.env"
  loop: "{{ services }}"

- name: Create Docker networks
  community.docker.docker_network:
    name: "{{ item }}"
  loop: "{{ networks }}"

- name: Start containers
  community.docker.docker_compose_v2:
    project_src: "{{ docker_containers_dir }}/{{ item.name }}"
    state: present
  loop: "{{ services }}"
