services:
  gitea:
    image: docker.gitea.com/gitea:1.25.5
    container_name: gitea
    restart: unless-stopped
    volumes:
      - gitea_data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "2222:2222"
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.rule=Host(`gitea.omp.home`)"
      - "traefik.http.routers.gitea.entrypoints=web"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
volumes:
  gitea_data:
    external: true

networks:
  traefik-net:
    external: true
