---
- name: Add Docker repository on Debian
  ansible.builtin.deb822_repository:
    name: docker
    types:
      - deb
    uris:
      - https://download.docker.com/linux/debian
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
    components:
      - stable
    architectures:
      - amd64
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
