---
- name: Install dependencies for Docker
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - python3-debian
      - python3-requests
      - python3-docker

    state: present
    update_cache: true

- name: Add Docker repository
  ansible.builtin.deb822_repository:
    name: docker
    types:
      - deb
    uris:
      - https://download.docker.com/linux/debian
    suites:
      - "{{ ansible_facts['distribution_release'] }}"
    components:
      - stable
    architectures:
      - amd64
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add SSH user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
