---
- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - python3-debian
      - python3-requests
      - python3-docker
    state: present
    update_cache: true

- name: Configure Docker repository on Debian
  ansible.builtin.include_tasks: debian.yml
  when: ansible_facts['distribution'] == 'Debian'

- name: Configure Docker repository on Ubuntu
  ansible.builtin.include_tasks: ubuntu.yml
  when: ansible_facts['distribution'] == 'Ubuntu'

- name: Install Docker Engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present

- name: Ensure Docker is started and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add SSH user to docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
