services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - heimdall_config:/config
    ports:
      - "8085:80"
      #- "8443:443"
    restart: unless-stopped
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.rule=Host(`dashboard.omp.home`)"
      - "traefik.http.routers.heimdall.entrypoints=web"
      - "traefik.http.services.heimdall.loadbalancer.server.port=80"

volumes:
  heimdall_config:

networks:
  traefik-net:
    external: true
