services:
  kopia:
    image: kopia/kopia:latest
    hostname: kopia
    container_name: kopia
    restart: unless-stopped
    ports:
      - 51515:51515
    # Setup the server that provides the web gui
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${APP_USER}
      - --server-password=${APP_PASSWORD}
    environment:
      # Set repository password
      USER: ${APP_USER}
      KOPIA_PASSWORD: ${APP_PASSWORD}
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kopia.rule=Host(`kopia.omp.home`)"
      - "traefik.http.routers.kopia.entrypoints=web"
      - "traefik.http.services.kopia.loadbalancer.server.port=51515"
    volumes:
      - kopia_config:/app/config
      - kopia_cache:/app/cache
      - kopia_logs:/app/logs
      - ${STORAGE}/backups:/repository
      # Volumes for backup
      - qbittorrent_data:/data/qBittorrent
      - prowlarr_data:/data/prowlarr
      - sonarr_data:/data/sonarr
      - radarr_data:/data/radarr
      - jackett_data:/data/jackett
      - jellyfin_data:/data/jellyfin
      - gitea_data:/data/gitea
      - sftpgo_config:/data/filebrowser
      - flame_data:/data/flame
      - syncthing_config:/data/syncthing
      - dockhand_data:/data/dockhand

volumes:
  kopia_config:
    external: true
  kopia_cache:
  kopia_logs:
  qbittorrent_data:
    external: true
  prowlarr_data:
    external: true
  sonarr_data:
    external: true
  radarr_data:
    external: true
  jackett_data:
    external: true
  jellyfin_data:
    external: true
  gitea_data:
    external: true
  sftpgo_config:
    external: true
  flame_data:
    external: true
  syncthing_config:
    external: true
  dockhand_data:
    external: true

networks:
  traefik-net:
    external: true
